#!/usr/bin/env bash
# Script that setup a nginx web server on our server.

sudo apt update -y && apt upgrade -y
sudo apt install nginx -y

# Modify the default Nginx configuration file to include the "Hello World!" message
echo "Hello World!" | sudo tee /var/www/html/index.html > /dev/null

# Test the Nginx configuration and reload the service
sudo nginx -t && sudo /etc/init.d/nginx reload
