#!/usr/bin/env bash
# Bash script that configures an Ubuntu server with the below requirements.
cp /etc/hosts ~/hosts.new
sed -i 's/127.0.0.2/8.8.8.8/g' ~/hosts.new
echo "facebook.com	8.8.8.8" >> ~/hosts.new
cp -f ~/hosts.new /etc/hosts
